# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "vmd"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/83e50462-b687-4d46-9557-e1a192581bcc";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "nodiscard"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/04C2-629F";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # fileSystems."/home/orhun/windows_mount" = {
  #   device = "/dev/disk/by-uuid/02324ACE324AC67F";
  #   fsType = "ntfs-3g";
  # };

  boot.resumeDevice = "/dev/disk/by-uuid/83e50462-b687-4d46-9557-e1a192581bcc";
  swapDevices = [ { device = "/swap/swapfile"; } ];

  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u1u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
